export const FORMAL_ENCOUNTER_SEED = Object.freeze([
  { name: "獅王基準", description: "沒有特殊效果的單體首領，檢查隊伍基本攻防。", enemyIds: ["forest_tyrant"] },
  { name: "泉庭誘餌", description: "低生命誘餌保護治療核心，自癒前排拖長戰線。", enemyIds: ["life_chanter", "high_priest", "sleepy_healer"] },
  { name: "薄甲連牙", description: "全隊薄甲掩護前排三連擊，讓穿透與多段承傷各有價值。", enemyIds: ["bombard_pulser", "twin_serpent"] },
  { name: "白鐵倒數", description: "厚甲穿透前排拖延時間，後排在第十回合引爆全場。", enemyIds: ["forest_deer", "iron_fortress"] },
  { name: "爆羽火線", description: "開場傷害接上死亡爆破，逼迫隊伍處理傷害時序。", enemyIds: ["bombard_opener", "bombard_martyr", "swarm_boar"] },
  { name: "竹林風眼", description: "範圍攻擊藏在減傷守衛身後，必須突破保護或直取後排。", enemyIds: ["storm_archer", "bamboo_guard"] },
  { name: "深海替身", description: "後排刺客與最低生命追擊者，獅子以高攻擊力施壓。", enemyIds: ["endless_colossus", "royal_assassin", "forest_tyrant"] },
  { name: "封攻長城", description: "電鰻封鎖前排攻擊，陸龜以護甲拖延戰鬥。", enemyIds: ["attack_sealer", "shell_guard"] },
  { name: "霧沼三震", description: "開戰三段全體傷害後進入奇數回合閃避節奏。", enemyIds: ["shadow_assassin"] },
  { name: "存活威壓", description: "猴子與水獺依序排列；猴子攻擊力與生命上限為 6 × 我方目前存活角色數，水獺為 5/40 白板。", enemyIds: ["worker_living_enemy_power", "worker_living_enemy_guard"] },
  { name: "誘餌獵場", description: "後排治療核心、高攻中衛與低生命前衛組成多線壓力；跳蛛、獨角仙與蜜獾各有發揮空間，但一般輸出也能通關。", enemyIds: ["sleepy_healer", "swarm_piranha", "endless_colossus"] },
  { name: "孵蛋母雞", description: "母雞持續在前方孵化雞蛋，考驗清場速度與前線壓力控制。", enemies: [{ id: "worker_summoning_hen", name: "母雞", image: "/pet_images/enemies/hen.png", atk: 12, hp: 40, special: { roundFrontSummonEvery: 2, roundFrontSummonName: "雞蛋", roundFrontSummonImage: "/pet_images/enemies/egg.png", roundFrontSummonAtk: 4, roundFrontSummonHp: 3 } }] },
  { name: "死亡分裂", description: "羚羊死亡時分裂成兩個較弱個體，考驗範圍傷害與持續作戰。", enemyIds: ["worker_survival_splitter"] },
  { name: "駝羽風暴", description: "開場轟炸、死亡爆破與範圍普攻形成三種不同傷害波段。", enemyIds: ["storm_archer", "bombard_opener", "bombard_martyr"] },
]);
